function dXdt=sys_fly(t,X)
global m g L

dXdt = zeros(8,1);
theta1 = X(3);
theta2 = X(4);
theta1d = X(7);
theta2d= X(8);

dXdt(1) = X(5);
dXdt(2) = X(6);
dXdt(3) = X(7);
dXdt(4) = X(8);

tau=tau_calc(t);

% %%%%%%%%%% q5 only %%%%%%%%%%%%%%
% global theta12dd_desired
% theta12 = theta1+theta2;
% if theta12 > deg2rad(100)
%     theta12dd_desired = -5;
% elseif theta12 < deg2rad(50)
%     theta12dd_desired = 5;
% else
%     theta12dd_desired = 0;
% end
% tau=tau_q5(X);
% if tau > 10
%     tau = 10;
% elseif tau < -10
%     tau = -10;
% end
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%    The rest of the function was generated by the Symbolic Math Toolbox version 8.6.
rhs = temp_fly_qdd(L,g,m,tau,theta1,theta2,theta1d,theta2d);
dXdt(5:8) = rhs;
end