function dXdt = sys_stick(t,X)
global m g L
m=0.3;
g=10;
L=0.15;

dXdt = zeros(8,1);
x = X(1);
y = X(2);
theta1 = X(3);
theta2 = X(4);
xd = X(5);
yd = X(6);
theta1d = X(7);
theta2d= X(8);

dXdt(1) = X(5);
dXdt(2) = X(6);
dXdt(3) = X(7);
dXdt(4) = X(8);

tau=tau_calc(t);

%    The rest of the function was generated by the Symbolic Math Toolbox version 8.6.
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta2);
t5 = L.^2;
t6 = theta2.*2.0;
t7 = theta1d.^2;
t8 = theta2d.^2;
t12 = 1.0./m;
t9 = cos(t6);
t10 = sin(t6);
t11 = 1.0./t5;
t13 = t6+theta1;
t16 = L.*g.*m.*t2.*2.4e+1;
t18 = m.*t4.*t5.*theta1d.*theta2d.*4.0e+1;
t20 = m.*t4.*t5.*t8.*2.0e+1;
t14 = cos(t13);
t15 = t9.*1.8e+1;
t17 = -t16;
t19 = L.*g.*m.*t14.*6.0;
t21 = t15-6.7e+1;
t22 = 1.0./t21;
rhs = [0.0;0.0;t11.*t12.*t22.*(t17+t18+t19+t20-tau.*1.0e+1-t3.*tau.*1.2e+1+m.*t4.*t5.*t7.*2.0e+1+m.*t5.*t7.*t10.*1.2e+1).*(-3.0./2.0);t11.*t12.*t22.*(t17+t18+t19+t20-tau.*4.4e+1-t3.*tau.*2.4e+1+m.*t4.*t5.*t7.*8.8e+1+m.*t5.*t7.*t10.*2.4e+1+m.*t5.*t8.*t10.*1.2e+1+L.*g.*m.*cos(theta1+theta2).*1.6e+1-L.*g.*m.*cos(theta1-theta2).*1.8e+1+m.*t5.*t10.*theta1d.*theta2d.*2.4e+1).*(3.0./2.0)];

dXdt(5:8) = rhs;     
end
