function dXdt=sys_fly(t,X)
global m g L
m=0.3;
g=10;
L=0.15;

dXdt = zeros(8,1);
x = X(1);
y = X(2);
theta1 = X(3);
theta2 = X(4);
xd = X(5);
yd = X(6);
theta1d = X(7);
theta2d= X(8);

dXdt(1) = X(5);
dXdt(2) = X(6);
dXdt(3) = X(7);
dXdt(4) = X(8);

tau=tau_calc(t);

%    The rest of the function was generated by the Symbolic Math Toolbox version 8.6.
t2 = cos(theta2);
t3 = sin(theta2);
t4 = theta1+theta2;
t5 = L.^2;
t6 = theta2.*2.0;
t7 = theta1d.^2;
t8 = theta2d.^2;
t10 = 1.0./L;
t14 = 1.0./m;
t15 = -theta2;
t9 = cos(t6);
t11 = 1.0./t5;
t12 = cos(t4);
t13 = sin(t4);
t16 = t4+theta2;
t17 = t15+theta1;
t18 = cos(t17);
t19 = sin(t17);
t20 = t9.*9.0;
t21 = t20-8.9e+1;
t22 = 1.0./t21;
rhs = [-t10.*t14.*t22.*(t13.*tau.*1.5e+1-t19.*tau.*2.7e+1+m.*t5.*t7.*t12.*1.3e+1+m.*t5.*t8.*t12.*1.3e+1+m.*t5.*t7.*t18.*2.7e+1+m.*t5.*t8.*t18.*2.7e+1-m.*t5.*t7.*cos(t16).*3.0+m.*t5.*t7.*cos(theta1).*1.23e+2+m.*t5.*t12.*theta1d.*theta2d.*2.6e+1+m.*t5.*t18.*theta1d.*theta2d.*5.4e+1);-t10.*t14.*t22.*(t12.*tau.*-1.5e+1+t18.*tau.*2.7e+1-L.*g.*m.*8.9e+1+m.*t5.*t7.*t13.*1.3e+1+m.*t5.*t8.*t13.*1.3e+1+m.*t5.*t7.*t19.*2.7e+1+m.*t5.*t8.*t19.*2.7e+1-m.*t5.*t7.*sin(t16).*3.0+m.*t5.*t7.*sin(theta1).*1.23e+2+L.*g.*m.*t20+m.*t5.*t13.*theta1d.*theta2d.*2.6e+1+m.*t5.*t19.*theta1d.*theta2d.*5.4e+1);(t11.*t14.*(t2.*tau.*-6.0+m.*t3.*t5.*t7.*7.0+m.*t3.*t5.*t8.*7.0+m.*t2.*t3.*t5.*t7.*3.0+m.*t3.*t5.*theta1d.*theta2d.*1.4e+1).*-3.0)./(t2.^2.*9.0-4.9e+1);(t11.*t14.*(tau.*-2.0+m.*t3.*t5.*t7.*2.0+m.*t3.*t5.*t8+m.*t3.*t5.*theta1d.*theta2d.*2.0).*3.0)./(t2.*3.0-7.0)];

dXdt(5:8) = rhs;
end