function dXdt=sys_fly(t,X)
global m g L
m=0.3;
g=10;
L=0.15;

dXdt = zeros(8,1);
x = X(1);
y = X(2);
theta1 = X(3);
theta2 = X(4);
xd = X(5);
yd = X(6);
theta1d = X(7);
theta2d= X(8);

dXdt(1) = X(5);
dXdt(2) = X(6);
dXdt(3) = X(7);
dXdt(4) = X(8);

tau=tau_calc(t);

%    The rest of the function was generated by the Symbolic Math Toolbox version 8.6.
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta1+theta2;
t7 = L.^2;
t8 = theta2.*2.0;
t9 = theta1d.^2;
t10 = theta2d.^2;
t12 = 1.0./L;
t16 = 1.0./m;
t17 = -theta2;
t11 = cos(t8);
t13 = 1.0./t7;
t14 = cos(t6);
t15 = sin(t6);
t18 = t6+theta2;
t21 = t17+theta1;
t19 = cos(t18);
t20 = sin(t18);
t22 = cos(t21);
t23 = sin(t21);
t24 = t11.*9.0;
t25 = t24-8.9e+1;
t26 = 1.0./t25;
rhs = [-t12.*t16.*t26.*(t4.*tau.*-1.17e+2+t15.*tau.*1.5e+1+t20.*tau.*9.0-t23.*tau.*2.7e+1+m.*t2.*t7.*t9.*1.23e+2+m.*t7.*t9.*t14.*1.3e+1+m.*t7.*t10.*t14.*1.3e+1-m.*t7.*t9.*t19.*3.0+m.*t7.*t9.*t22.*2.7e+1+m.*t7.*t10.*t22.*2.7e+1+m.*t7.*t14.*theta1d.*theta2d.*2.6e+1+m.*t7.*t22.*theta1d.*theta2d.*5.4e+1);-t12.*t16.*t26.*(t2.*tau.*1.17e+2-t14.*tau.*1.5e+1-t19.*tau.*9.0+t22.*tau.*2.7e+1-L.*g.*m.*8.9e+1+m.*t4.*t7.*t9.*1.23e+2+m.*t7.*t9.*t15.*1.3e+1+m.*t7.*t10.*t15.*1.3e+1-m.*t7.*t9.*t20.*3.0+m.*t7.*t9.*t23.*2.7e+1+m.*t7.*t10.*t23.*2.7e+1+L.*g.*m.*t24+m.*t7.*t15.*theta1d.*theta2d.*2.6e+1+m.*t7.*t23.*theta1d.*theta2d.*5.4e+1);(t13.*t16.*(tau.*-1.4e+1-t3.*tau.*6.0+m.*t5.*t7.*t9.*7.0+m.*t5.*t7.*t10.*7.0+m.*t3.*t5.*t7.*t9.*3.0+m.*t5.*t7.*theta1d.*theta2d.*1.4e+1).*-3.0)./(t3.^2.*9.0-4.9e+1);(t13.*t16.*(tau.*-4.0+m.*t5.*t7.*t9.*2.0+m.*t5.*t7.*t10+m.*t5.*t7.*theta1d.*theta2d.*2.0).*3.0)./(t3.*3.0-7.0)];

dXdt(5:8) = rhs;
end