function rhs = temp_stick(L,g,m,tau,theta1,theta2,theta1d,theta2d)
%TEMP_STICK
%    RHS = TEMP_STICK(L,G,M,TAU,THETA1,THETA2,THETA1D,THETA2D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Jul-2021 20:04:20

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = L.^2;
t7 = theta2.*2.0;
t8 = theta2.*3.0;
t9 = theta2.*4.0;
t10 = theta1d.^2;
t11 = theta2d.^2;
t16 = 1.0./L;
t18 = 1.0./m;
t12 = cos(t7);
t13 = t3.^2;
t14 = sin(t7);
t15 = sin(t8);
t17 = 1.0./t6;
t19 = -t7;
t20 = t7+theta1;
t21 = cos(t20);
t22 = t19+theta1;
t24 = t13.*9.0;
t23 = cos(t22);
t25 = t24-4.9e+1;
t26 = 1.0./t25;
rhs = [t16.*t18.*t26.*tau.*(t2.*t5.*1.4e+1-t3.*t4.*4.0).*(-3.0./2.0);t16.*t18.*t26.*tau.*(t2.*t3.*4.0+t4.*t5.*1.4e+1).*(-3.0./2.0);(t17.*t18.*(t3.*tau.*6.96e+2-tau.*cos(t8).*1.08e+2-m.*t5.*t6.*t10.*9.35e+2-m.*t5.*t6.*t11.*9.35e+2-m.*t6.*t10.*t14.*5.34e+2+m.*t6.*t10.*t15.*4.5e+1+m.*t6.*t11.*t15.*4.5e+1+L.*g.*m.*cos(t9+theta1).*(2.7e+1./2.0)+m.*t6.*t10.*sin(t9).*2.7e+1+L.*g.*m.*t2.*1.0815e+3-L.*g.*m.*t21.*3.21e+2-L.*g.*m.*t23.*5.4e+1-m.*t5.*t6.*theta1d.*theta2d.*1.87e+3+m.*t6.*t15.*theta1d.*theta2d.*9.0e+1).*-3.0)./(t12.*-2.205e+3+t12.^2.*1.62e+2+5.963e+3);(t17.*t18.*(tau.*-2.68e+2+t12.*tau.*7.2e+1+m.*t5.*t6.*t10.*5.8e+2+m.*t5.*t6.*t11.*1.22e+2+m.*t6.*t10.*t14.*3.6e+1-m.*t6.*t10.*t15.*3.6e+1+m.*t6.*t11.*t14.*5.4e+1-m.*t6.*t11.*t15.*1.8e+1-L.*g.*m.*cos(t8+theta1).*9.0+L.*g.*m.*cos(theta1+theta2).*1.39e+2-L.*g.*m.*cos(theta1-theta2).*9.0e+1-L.*g.*m.*t2.*1.65e+2+L.*g.*m.*t21.*1.8e+1+L.*g.*m.*t23.*2.7e+1+m.*t5.*t6.*theta1d.*theta2d.*2.44e+2+m.*t6.*t14.*theta1d.*theta2d.*1.08e+2-m.*t6.*t15.*theta1d.*theta2d.*3.6e+1).*(3.0./2.0))./(t3.*2.55e+2+t13.*2.52e+2-t3.^3.*1.08e+2-5.95e+2)];
