function lambdat = temp_lam_t(L,g,m,tau,theta1,theta2,theta1d,theta2d)
%TEMP_LAM_T
%    LAMBDAT = TEMP_LAM_T(L,G,M,TAU,THETA1,THETA2,THETA1D,THETA2D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Jul-2021 05:35:21

t2 = theta1+theta2;
t3 = L.^2;
t4 = theta1.*2.0;
t5 = theta2.*2.0;
t6 = theta1d.^2;
t7 = theta2d.^2;
t9 = -theta2;
t8 = cos(t2);
t10 = t2+theta2;
t11 = t9+theta1;
t12 = cos(t11);
lambdat = (tau.*sin(t2).*2.1e+1+tau.*sin(t10).*9.0-tau.*sin(t11).*2.7e+1-tau.*sin(theta1).*2.7e+1+m.*t3.*t6.*t8.*1.0e+1+m.*t3.*t7.*t8.*1.0e+1+m.*t3.*t6.*t12.*1.8e+1+m.*t3.*t7.*t12.*1.8e+1-L.*g.*m.*sin(t4).*2.7e+1-m.*t3.*t6.*cos(t10).*6.0+m.*t3.*t6.*cos(theta1).*9.0e+1+L.*g.*m.*sin(t2.*2.0).*3.0+m.*t3.*t8.*theta1d.*theta2d.*2.0e+1+m.*t3.*t12.*theta1d.*theta2d.*3.6e+1)./(L.*(cos(t5).*9.0-2.3e+1).*2.0);
