function M = temp_M(L,m,theta1,theta2)
%TEMP_M
%    M = TEMP_M(L,M,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    16-Jul-2021 18:44:06

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = theta1+theta2;
t6 = L.^2;
t7 = m.*2.0;
t8 = t2.*3.0;
t9 = t3.*3.0;
t10 = t4.*3.0;
t11 = cos(t5);
t12 = sin(t5);
t13 = t9+2.0;
t14 = L.*m.*t11;
t15 = L.*m.*t12;
t16 = t8+t11;
t17 = t10+t12;
t18 = -t15;
t19 = L.*m.*t16;
t20 = L.*m.*t17;
t21 = m.*t6.*t13.*(2.0./3.0);
t22 = -t20;
M = reshape([t7,0.0,t22,t18,0.0,t7,t19,t14,t22,t19,m.*t6.*(t13+3.0).*(4.0./3.0),t21,t18,t14,t21,m.*t6.*(4.0./3.0)],[4,4]);
