function rhs = temp_stick_qdd(L,g,m,tau,theta1,theta2,theta1d,theta2d)
%TEMP_STICK_QDD
%    RHS = TEMP_STICK_QDD(L,G,M,TAU,THETA1,THETA2,THETA1D,THETA2D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Jul-2021 05:35:20

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta2);
t5 = L.^2;
t6 = theta2.*2.0;
t7 = theta1d.^2;
t8 = theta2d.^2;
t12 = 1.0./m;
t9 = cos(t6);
t10 = sin(t6);
t11 = 1.0./t5;
t13 = t6+theta1;
t16 = L.*g.*m.*t2.*2.7e+1;
t18 = m.*t4.*t5.*theta1d.*theta2d.*4.8e+1;
t20 = m.*t4.*t5.*t8.*2.4e+1;
t14 = cos(t13);
t15 = t9.*9.0;
t17 = -t16;
t19 = t15-2.3e+1;
t21 = L.*g.*m.*t14.*9.0;
t22 = 1.0./t19;
rhs = [0.0;0.0;t11.*t12.*t22.*(t17+t18+t20+t21-tau.*1.2e+1-t3.*tau.*1.8e+1+m.*t4.*t5.*t7.*2.4e+1+m.*t5.*t7.*t10.*1.8e+1).*(-1.0./2.0);(t11.*t12.*t22.*(t17+t18+t20+t21-tau.*6.0e+1-t3.*tau.*3.6e+1+m.*t4.*t5.*t7.*1.2e+2+m.*t5.*t7.*t10.*3.6e+1+m.*t5.*t8.*t10.*1.8e+1+L.*g.*m.*cos(theta1+theta2).*2.1e+1-L.*g.*m.*cos(theta1-theta2).*2.7e+1+m.*t5.*t10.*theta1d.*theta2d.*3.6e+1))./2.0];
