function tau_better=tau_q5(X)
global m g L
global theta12dd_desired
theta1 = X(3);
theta2 = X(4);
theta1d = X(7);
theta2d= X(8);

tau=0;
%    The rest of the function was generated by the Symbolic Math Toolbox version 8.6.
rhs = temp_fly_qdd(L,g,m,tau,theta1,theta2,theta1d,theta2d);
xdd = rhs(1);
ydd = rhs(2);
theta1dd = rhs(3);
theta12 = theta1+theta2;
a = (L*m*(- 6*L*sin(theta1 - theta12)*theta1d^2 + 3*g*cos(theta12) + 3*ydd*cos(theta12) - 3*xdd*sin(theta12) + 6*L*theta1dd*cos(theta1 - theta12)))/3 ; 
b = (4*L^2*m)/3;
tau_better = b * theta12dd_desired + a;
end